using STROOP.Forms;
using STROOP.Managers;
using STROOP.Structs.Configurations;
using STROOP.Utilities;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace STROOP.Structs
{
    public static class SkribblioUtilities
    {
        private static readonly List<string> _words =
            new List<string>()
            {
                // Mission Names
                "Big Bob-omb on the Summit",
                "Footrace with Koopa the Quick",
                "Shoot to the Island in the Sky",
                "Find the 8 Red Coins",
                "Mario Wings to the Sky",
                "Behind Chain Chomp's Gate",

                "Chip Off Whomp's Block",
                "To the Top of the Fortress",
                "Shoot into the Wild Blue",
                "Red Coins on the Floating Isle",
                "Fall onto the Caged Island",
                "Blast Away the Wall",

                "Plunder in the Sunken Ship",
                "Can the Eel Come Out to Play?",
                "Treasure of the Ocean Cave",
                "Red Coins on the Ship Afloat",
                "Blast to the Stone Pillar",
                "Through the Jet Stream",

                "Slip Slidin' Away",
                "Li'l Penguin Lost",
                "Big Penguin Race",
                "Frosty Slide for 8 Red Coins",
                "Snowman's Lost His Head",
                "Wall Kicks Will Work",

                "Go On a Ghost Hunt",
                "Ride Big Boo's Merry-Go-Round",
                "Secret of the Haunted Books",
                "Seek the 8 Red Coins",
                "Big Boo's Balcony",
                "Eye to Eye in the Secret Room",

                "Swimming Beast in the Cavern",
                "Elevate for 8 Red Coins",
                "Metal-Head Mario Can Move!",
                "Navigating the Toxic Maze",
                "A-Maze-ing Emergency Exit",
                "Watch for Rolling Rocks",

                "Boil the Big Bully",
                "Bully the Bullies",
                "8-Coin Puzzle with 15 Pieces",
                "Red-Hot Log Rolling",
                "Hot-Foot-It into the Volcano",
                "Elevator Tour in the Volcano",

                "In the Talons of the Big Bird",
                "Shining Atop the Pyramid",
                "Inside the Ancient Pyramid",
                "Stand Tall on the Four Pillars",
                "Free Flying for 8 Red Coins",
                "Pyramid Puzzle",

                "Board Bowser's Sub",
                "Chests in the Current",
                "Pole-Jumping for Red Coins",
                "The Manta Ray's Reward",
                "Collect the Caps...",

                "Snowman's Big Head",
                "Chill with the Bully",
                "In the Deep Freeze",
                "Whirl from the Freezing Pond",
                "Shell Shreddin' for Red Coins",
                "Into the Igloo",

                "Shocking Arrow Lifts!",
                "Top O' the Town",
                "Secrets in the Shallows & Sky",
                "Express Elevator--Hurry Up!",
                "Go to Town for Red Coins",
                "Quick Race Through Downtown!",

                "Scale the Mountain",
                "Mystery of the Monkey Cage",
                "Scary 'Shrooms Red Coins",
                "Mysterious Mountainside",
                "Breathtaking View from Bridge",
                "Blast to the Lonely Mushroom",

                "Pluck the Piranha Flower",
                "The Tip Top of the Huge Island",
                "Rematch with Koopa the Quick",
                "Five Itty Bitty Secrets",
                "Wiggler's Red Coins",
                "Make Wiggler Squirm",

                "Roll into the Cage",
                "The Pit and the Pendulums",
                "Get a Hand",
                "Stomp on the Thwomp",
                "Timed Jumps on Moving Bars",
                "Stop Time for Red Coins",

                "Cruiser Crossing the Rainbow",
                "The Big House in the Sky",
                "Coins Amassed in a Maze",
                "Swingin' in the Breeze",
                "Tricky Triangles!",
                "Somewhere Over the Rainbow",

                "100 Coin Star",

                // Course Names
                "Bob-omb Battlefield",
                "Whomp's Fortress",
                "Jolly Roger Bay",
                "Cool Cool Mountain",
                "Big Boo's Haunt",
                "Hazy Maze Cave",
                "Lethal Lava Land",
                "Shifting Sand Land",
                "Dire Dire Docks",
                "Snowman's Land",
                "Wet-Dry World",
                "Tall Tall Mountain",
                "Tiny-Huge Island",
                "Tick Tock Clock",
                "Rainbow Ride",

                "Tower of the Wing Cap",
                "Cavern of the Metal Cap",
                "Vanish Cap under the Moat",
                "The Princess's Secret Slide",
                "The Secret Aquarium",
                "Wing Mario over the Rainbow",
                "Bowser in the Dark World",
                "Bowser in the Fire Sea",
                "Bowser in the Sky",
                "Castle Grounds",
                "Lobby",
                "Basement",
                "Upstairs",
                "Courtyard",

                // Glitches & Tricks & Terminology
                "Parallel Universe",
                "Pedro Spot",
                "Hyperspeed Walking",
                "Hyperspeed Water Sliding",
                "Hyperspeed Wall Kicking",
                "Hyperspeed Grinding",
                "Wind Hyperspeed",
                "MIPS Clip",
                "Backwards Long Jump",
                "Fly Guy Manipulation",
                "Invisible Wall",
                "Glitchy Ledge Grab",
                "Glitchy Wall Kick",
                "Cloning",
                "Cloned Coin",
                "Beached Bubba",
                "Time Stop",
                "Lakitu Skip",
                "Cannonless",
                "Owlless",
                "Impossible Coin",
                "Moat Door Skip",
                "Misalignment",
                "Goomba Bridge",
                "Goomba Staircase",
                "Goomba Ladder",
                "Hat in Hand",
                "Object Displacement",
                "Infinite Coin Glitches",
                "Handsfree Holding",
                "Handsfree",
                "Transport Cloning",
                "Premature Clone",
                "Interference Clone",
                "RNG Manipulation",
                "RNG",
                "Goomba Chase Extension",
                "Scuttlebug Transportation",
                "Scuttlebug Raising",
                "Scuttlebug Jamboree",
                "Pendulum Manipulation",
                "10k Glitch",
                "QPU",
                "PU",
                "Supersaturated Bob-omb",
                "Divide by Zero",
                "Rotational Platform Displacement",
                "Spawning Displacement",
                "Clip",
                "Glitch",
                "Handsfree Teleport",
                "Bob-omb Clip",
                "Quarter Step",
                "Float Coarseness",
                "Overflow",
                "Underflow",
                "M25",
                "Intended Next Position",
                "Ghost Hack",
                "Frame Walk",
                "Mystery Goomba",
                "Wrong Warp",
                "De Facto Speed",
                "Game Crash",
                "Softlock",
                "Global Timer",
                "Downwarp",
                "Upwarp",

                // Meta SM64
                "Super Mario 64",
                "Console",
                "Nintendo 64",
                "Virtual Console",
                "Wii",
                "Wii VC",
                "Wii U",
                "Wii U VC",
                "Nintendo 64 Disk Drive",
                "Emulator",
                "Mupen",
                "Project64",
                "Bizhawk",
                "TAS",
                "Tool Assisted Speedrun",
                "Tool Assisted Superplay",
                "STROOP",
                "Controller",
                "Reset",
                "Marathon",
                "RTA",
                "Real-Time Attack",
                "Speedrun",
                "No Reset Run",
                "Competition",
                "Freerun",
                "Community Freerun",
                "Cartridge Tilting",
                "Decomp",
                "MHS",
                "Cheat Code",
                "Game Shark",
                "Frame",
                "TASBot",
                "Improvement",
                "Hack",
                "Side BLJ",
                "Lobby BLJ",
                "Save & Continue",
                "Save & Quit",
                "Continue Don't Save",

                // People
                "pannenkoek2012",
                "Ethan White",
                "thestickman391",
                "plush",
                "1ted59",
                "simpleflips",
                "Nathaniel Bandy",
                "Dom Dunc",
                "Bluemania",
                "bad_boot",
                "TJ Henry Yoshi",

                // Abstract Things
                "Camera",
                "Mario Cam",
                "Lakitu Cam",
                "Fixed Cam",
                "HOLP",
                "HUD",
                "Object Slot",
                "Vacant Slot",
                "Child",
                "Parent",
                "Object",
                "Triangle",
                "Debug",
                "Collision",
                "Map",
                "Level",
                "Course",
                "Stage",
                "Area",
                "Slope",
                "CPU",
                "Floor",
                "Wall",
                "Ceiling",
                "Painting",
                "Nintendo",
                "Miyamoto",
                "Water",
                "Lava",
                "Credits",
                "Music",
                "Power",
                "Skybox",
                "Sky",
                "Ground",
                "Fall Damage",
                "Damage",
                "Eye",
                "Nose",
                "Mouth",
                "Hair",
                "Moustache",
                "Overalls",
                "Blink",
                "Cutscene",
                "Angle",
                "Terrain",
                "Hitbox",
                "Speed",
                "Graphics",
                "Animation",
                "Velocity",
                "FOV",
                "Out of Bounds",
                "Button Mashing",
                "Pause Buffering",
                "Pause",

                // Memes
                "Bait",
                "Half A Press",
                "Iwerp",

                // Menu
                "Copy",
                "Paste",
                "Score",
                "Game Over",
                "Die",
                "Heal",
                "Press Start",
                "Stereo",
                "File",
                "Mono",
                "Headset",
                "Return",
                "Cursor",
                "Arrow",
                "Menu",
                "Select",
                "Option",

                // Controller
                "A Button",
                "B Button",
                "C Buttons",
                "Z Button",
                "R Button",
                "L Button",
                "Start Button",
                "D Pad",
                "Control Stick",
                "Joystick",
                "Analog Stick",

                // Objects
                "! Switch",
                "1-Up",
                "Amp",
                "Arrow Lift",
                "Baby Penguin",
                "Big Boo",
                "Big Bully",
                "Big Mr. I",
                "Bird",
                "Blargg",
                "Blue Coin",
                "Blue Coin Block",
                "Bob-omb",
                "Bob-omb Buddy",
                "Bomp",
                "Boo",
                "Boo Key",
                "Bookend",
                "Bookshelf",
                "Bowling Ball",
                "Bowser",
                "Bowser Puzzle Piece",
                "Bowser's Sub",
                "Bub",
                "Bubba",
                "Bubble",
                "Bullet",
                "Bullet Bill",
                "Bullet Bill Blaster",
                "Bulletin Board",
                "Bully",
                "Butterfly",
                "Camera Lakitu",
                "Cannon Base",
                "Cannon Grills",
                "Cannon Lid",
                "Cannon Shaft",
                "Cap",
                "Cap Switch",
                "Carousel",
                "Carpet",
                "Chain",
                "Chain Chomp",
                "Checkpoint",
                "Chest",
                "Chest Bottom",
                "Chest Lid",
                "Chill Bully",
                "Chuckya",
                "Clam",
                "Coffin",
                "Cog",
                "Coin Arrow",
                "Coin Block",
                "Coin Line",
                "Coin Ring",
                "Coin Spawner",
                "Cork Box",
                "Crazy Box",
                "Crystal Tap",
                "Dirt",
                "Donut Lift",
                "Door",
                "Dorrie",
                "Drawbridge",
                "Dust",
                "Eel",
                "Elevator",
                "Exclamation Mark",
                "Explosion",
                "Express Elevator",
                "Eyerok",
                "Falling Block",
                "Falling Plank",
                "Fire",
                "Fire Bar",
                "Fire Spitter",
                "Fish",
                "Fish Spawner",
                "Flag",
                "Flame",
                "Flame Breath",
                "Fly Guy",
                "Fuse",
                "Fwoosh",
                "Gate",
                "Glow",
                "Goomba",
                "Grand Star",
                "Grindel",
                "Hand",
                "Hat",
                "Haunted Chair",
                "Heave-Ho",
                "Hoot",
                "Hour Hand",
                "Igloo Barrier",
                "Item Block",
                "King Bob-omb",
                "King Whomp",
                "Klepto",
                "Koopa",
                "Koopa the Quick",
                "Lakitu",
                "Lakitu Cloud",
                "Landscape Visual",
                "Leaf",
                "Life",
                "Loose Floor Panel",
                "Mad Piano",
                "Manta Ray",
                "Manta Ring",
                "Mario",
                "Mario's Cap",
                "Merry-Go-Round",
                "Metal Cap",
                "Metal Cap Switch",
                "Minute Hand",
                "MIPS",
                "Mist",
                "Moat Grills",
                "Moneybag",
                "Monkey Cage",
                "Monty Mole",
                "Mother Penguin",
                "Moving Bar",
                "Mr. Blizzard",
                "Mr. I",
                "Openable Gate",
                "Palm Tree",
                "Peach",
                "Pebble",
                "Penguin",
                "Pine Tree",
                "Piranha Plant",
                "Pit Block",
                "Podoboo",
                "Pokey",
                "Pole",
                "Power Star",
                "Pushable Block",
                "Pyramid Top",
                "Racing Penguin",
                "Red Coin",
                "Red Coin Star",
                "Ripples",
                "Rolling Log",
                "Rolling Rock",
                "Sand",
                "Scuttlebug",
                "Seaweed",
                "Secret",
                "Seesaw Platform",
                "Shard",
                "Shell",
                "Shell Block",
                "Shockwave",
                "Shortcut",
                "Sign",
                "Skeeter",
                "Ski Lift",
                "Skull Crate",
                "Smoke",
                "Snow",
                "Snow Mound",
                "Snowball",
                "Snowman",
                "Snufit",
                "Sparkles",
                "Spindel",
                "Spindrift",
                "Spinning Heart",
                "Spiny",
                "Splash",
                "Springy Staircase",
                "Star Block",
                "Star Door",
                "Star Marker",
                "Sushi",
                "Swing",
                "Swooper",
                "Teleporter",
                "Thwomp",
                "Toad",
                "Tornado",
                "Tower",
                "Tox Box",
                "Treadmill",
                "Tree",
                "Tricky Triangles",
                "Tweester",
                "Ukiki",
                "Unagi",
                "Vanish Cap",
                "Vanish Cap Switch",
                "Volcano",
                "Walking Penguin",
                "Warp",
                "Warp Pipe",
                "Water Bomb",
                "Water Bomb Shadow",
                "Water Shell",
                "Whirlpool",
                "Whomp",
                "Wiggler",
                "Wing Cap",
                "Wing Cap Switch",
                "Yellow Coin",
                "Yellow Triangle",
                "Yoshi",
                "Yoshi Egg",
  
                // Challenges
                "A Button Challenge",
                "B Button Challenge",
                "Z Button Challenge",
                "ABZ Button Challenge",
                "RTABC",
                "ABC",
                "No Joystick Allowed",
                "No Buttons Allowed",
                "CCC Challenge",
                
                // Moves & Actions & States
                "Single Jump",
                "Double Jump",
                "Triple Jump",
                "Special Triple Jump",
                "Wall Kick",
                "Sideflip",
                "Somersault",
                "Long Jump",
                "Run",
                "Walk",
                "Flutter Kick",
                "Breast Stroke",
                "Crouch",
                "Crawl",
                "Crouch Slide",
                "Backflip",
                "Side Somersault",
                "Backward Somersault",
                "Climb",
                "Fly",
                "Jump Kick",
                "Slide Kick",
                "Trip",
                "Breakdance",
                "Grab",
                "Throw",
                "Pick Up",
                "Hold",
                "Ground Pound",
                "Fall",
                "Sleep",
                "Wake Up",
                "Open",
                "Close",
                "Transparent",
                "Intangible",
                "Invincible",
                "Suffocate",
                "Cough",
                "Shiver",
                "Dive",
                "Rollout",
                "Hop",
                "Death",
                "Eaten",
                "Electrocuted",
                "Shocked",
                "Sit",
                "Handstand",
                "Lava Boost",
                "Ledge Grab",
                "Knockback",
                "Skid",
                "Release",

                // Miscellaneous Terms
                "Mesh",
                "Wire Net",
                "Face",
                "Stretch",
                "Steps",
                "Stairs",
                "Luigi",
                "Dinosaur",
                "Dragon",
                "Rug",
                "Hill",
                "Read",
                "Dud",
                "Alcove",
                "Waterfall",
                "Path",
                "Ramp",
                "Lake",
                "Pond",
                "Rail",
                "Fence",
                "Corner",
                "Talk",
                "Speech",
                "Text",
                "Box",
                "Flower Patch",
                "Flower",
                "Rock",
                "Stone",
                "Wooden Post",
                "Letter",
                "Roll",
                "Mountain",
                "Grass",
                "Shadow",
                "Reflection",
                "Fog",
                "Peak",
                "Summit",
                "Island",
                "Race",
                "Field",
                "Fortress",
                "Block",
                "Blue",
                "Float",
                "Star",
                "Push",
                "Move",
                "Squish",
                "Key",
                "Tired",
                "Collect",
                "Bridge",
                "Balcony",
                "Pillar",
                "Column",
                "Break",
                "Oscillate",
                "Window",
                "Cage",
                "Exit",
                "Ship",
                "Boat",
                "Sink",
                "Rise",
                "Play",
                "Treasure",
                "Blast",
                "Bay",
                "Cave",
                "Slip",
                "Little",
                "Big",
                "Head",
                "Body",
                "Work",
                "Cool",
                "Platform",
                "Pedestal",
                "Lure",
                "Bonk",
                "Hall",
                "Hallway",
                "Ghost",
                "Statue",
                "Hunt",
                "Ride",
                "Haunted",
                "Room",
                "Shed",
                "Mansion",
                "House",
                "Castle",
                "Piano",
                "Mad",
                "Chair",
                "Book",
                "Molding",
                "Shine",
                "Light",
                "Hole",
                "Vibrate",
                "Shake",
                "Wiggle",
                "Teeth",
                "Roof",
                "Beast",
                "Swim",
                "Toxic",
                "Toxic Maze",
                "Emergency",
                "Maze",
                "Death Barrier",
                "Black Room of Death",
                "Lantern",
                "Black Hole",
                "Underground",
                "Lunge",
                "Mole",
                "Bat",
                "Saddle",
                "Talon",
                "Condor",
                "Vulture",
                "Ancient",
                "Pyramid",
                "Tall",
                "Puzzle",
                "Quicksand",
                "Track",
                "Hieroglyphics",
                "Oasis",
                "Coin",
                "Banister",
                "Board",
                "Current",
                "Jet Stream",
                "Reward",
                "Dock",
                "Tunnel",
                "Mirror",
                "Freeze",
                "Igloo",
                "Wet",
                "Dry",
                "Town",
                "Shallow",
                "Deep",
                "Spin",
                "Scale",
                "Mystery",
                "Scary",
                "Mushroom",
                "Lonely",
                "Lonely Mushroom",
                "Tiny",
                "Huge",
                "Squirm",
                "Pit",
                "Stomp",
                "Clock",
                "Rotate",
                "Gear",
                "Cube",
                "Rainbow",
                "Flying Carpet",
                "Mast",
                "Wing",
                "Oar",
                "Spire",
                "Aquarium",
                "Crystal",
                "Shoot",
                "Brick",
                "Fight",
                "Battle",
                "Axle",
                "Texture",
                "Pattern",
                "Bomb",
                "Blow",
                "Heavy",
                "Owl",
                "Barbed Wire",

                // Dialog & Text
                "Smack",
                "Middle",
                "Comrade",
                "Meadow",
                "Powerful",
                "Enemy",
                "Powerful",
                "Side",
                "Peace",
                "Love",
                "Voyage",
                "Mountaintop",
                "Scam",
                "Huff",
                "Puff",
                "Win",
                "Lose",
                "Scary",
                "Train",
                "Home",
                "Windswept Valley",
                "Shiny",
                "Shred",
                "Lord",
                "Kaboom",
                "Escape",
                "Foot",
                "World",
                "Royal",
                "Turf",
                "Buzzer",
                "Savings",
                "Mach 1 Sprint Shoes",
                "Cake",
                "Film",
                "Season",
                "Instructions",
                "Sled",
                "Surrender",
                "Whisper",
                "Gift",
                "King",
                "Princess",
                "Cold Cold Crevasse",
                "Flap",
                "Pasta",
                "Master",
                "Hop",
                "Skip",
                "Distance",
                "Slippery",
                "Champion",
                "Baby",
                "Herring",
                "Ice cube",
                "Parent",
                "Oxygen",
                "Frostbite",
                "Mad",
                "Bump",
                "Danger",
                "Shelter",
                "Prison",
                "City",
                "Trap",
                "Date",
                "Tea",
                "Ghoul Medal",
                "Santa Claus",
                "Cabin",
                "Friend",
                "Gust",
                "Minion",
                "Animal",
                "Tread",
                "Peak",
                "Blastoff",
                "Terror",
                "Shoulder",
                "Road",
                "Fun",
                "Gravel",
                "Intruder",
                "Solid",
                "Center",
                "Airplane",
                "Seal",
                "Display",
                "Power Meter",
                "Meter",
                "Princess",
                "Toadstool",
                "Up",
                "Down",
                "Left",
                "Right",
                "Forward",
                "Back",
                "Inside",
                "Outside",
                "Uncle",
                "Peace",
                "Ant",
                "Flea",
                "Bug",
                "Injury",
                "Swallow",
                "Smother",
                "Sink",
                "Fast",
                "Slow",
                "Bounce",
                "Adventure",
                "Knock",
                "Linguine",
            };

        public static void ShowWords()
        {
            List<string> randomWords = ControlUtilities.Randomize(_words);
            InfoForm.ShowValue(
                String.Join(",", randomWords),
                "Skribbl.io Words",
                "Skribbl.io Words");
        }
    }
}
